services:
  postgres:
    image: 'postgres:latest'
    environment:
      - 'POSTGRES_DB=bank-sys'
      - 'POSTGRES_PASSWORD=postgres'
      - 'POSTGRES_USER=postgres'
    ports:
      - '5432:5432'
    volumes:
      - postgres_data:/var/lib/postgresql/data
    networks:
      - bank-net

volumes:
  postgres_data:

networks:
  bank-net:
    driver: bridge
